logger.root_level: "INFO"

database.protocol: "postgresql+psycopg"
database.user: "test_user"
database.password: "test_password"
database.host: "localhost"
database.port: "5432"
database.database: "testdb"

trino_client.host: localhost
trino_client.port: "8081"
trino_client.username: admin

dbapi_connector.client_type: trino
dbapi_connector.data_object_table_column_query: |-
  WITH attrs (attribute_key, attribute_value, fq_name) AS (
    SELECT * FROM (VALUES 
      ('ad_group', 'moat_users_gl', 'datalake.logistics.shippers'),
      ('ad_group', 'MARKETING_ANALYSTS_GL', 'datalake.logistics.regions'),
      ('ad_group', 'SALES_ANALYSTS_GL', 'datalake.logistics.territories')
    ) AS v(attribute_key, attribute_value, fq_name)
  )
  SELECT tbls.fq_name, attribute_key, attribute_value
  FROM (
    SELECT table_catalog || '.' || table_schema || '.' || table_name AS fq_name
    FROM datalake.information_schema.tables
  ) AS tbls
  JOIN attrs ON tbls.fq_name = attrs.fq_name
