logger.root_level: "INFO"

database.protocol: "postgresql+psycopg"
database.user: "test_user"
database.password: "test_password"
database.host: "localhost"
database.port: "5432"
database.database: "testdb"

trino_client.host: localhost
trino_client.port: "8081"
trino_client.username: admin

dbapi_connector.client_type: trino
dbapi_connector.data_object_table_column_query: |-
  select fq_name, object_type from (
      select table_catalog || '.' || table_schema || '.' || table_name as fq_name, 'table' as object_type
      from datalake.information_schema.tables
      where table_schema <> 'information_schema'
      union all
      select table_catalog || '.' || table_schema || '.' || table_name || '.' || column_name as fq_name, 'column' as object_type
      from datalake.information_schema.columns
      where table_schema <> 'information_schema'
  )
  order by fq_name