site_name: Permitta Core
theme:
  name: material
  features:
    - navigation.expand
    - navigation.path
repo_url: https://github.com/permitta/permitta-core
dev_addr: localhost:8001

# https://github.com/squidfunk/mkdocs-material/blob/master/mkdocs.yml

nav:
  - Home: index.md
  - Trino and OPA: trino_and_opa.md
  - Extending Permitta-core: extensions.md
  - Security:
      - API Authentication: security/auth.md
  - Configuration:
      - Configuration File: config/configuration.md
      - Configuration Properties: config/properties.md
  - Deployment: deployment.md
  - Developer Setup: developer_setup.md
