logger.root_level: "INFO"

database.protocol: "postgresql+psycopg"
database.user: "test_user"
database.password: "test_password"
database.host: "localhost"
database.port: "5432"
database.database: "permitta"
database.seed_data_path: "permitta/seed_data"

trino_client.host: localhost
trino_client.port: "8081"
trino_client.username: admin

dbapi_connector.client_type: trino
dbapi_connector.data_object_table_column_query: |-
  select table_catalog || '.' || table_schema || '.' || table_name as fq_table_name
  from datalake.information_schema.tables
dbapi_connector.table_key: fq_table_name