# unit test items - do not remove
common.db_connection_string: "sqlite:///:memory:"
common.super_secret: "https:/domain?username=$FLASK_SECRET_KEY"

logger.root_level: "INFO"

flask.secret_key: "$FLASK_SECRET_KEY"

database.protocol: "postgresql+psycopg"
database.user: "postgres"
database.password: "password"
database.host: "localhost"
database.port: "5432"
database.database: "unittest"
database.seed_data_path: "permitta-core/test/seed_data"

connector.json_file.principals.file_path: "config/principals.json"
oidc_auth_provider.issuer: "http://example.com/realms/permitta"
oidc_auth_provider.client_id: "permitta-client"
oidc_auth_provider.client_secret: "super-secret"

opa_authz_provider.policy_name: "permitta/authz"
opa_authz_provider.policy_file_path: "opa/permitta/authz.rego"

ldap_client.host: localhost
ldap_client.port: "3890"
ldap_client.base_dn: dc=example,dc=com
ldap_client.user_dn: uid=admin,ou=people,dc=example,dc=com
ldap_client.password: changeme
ldap_client.user_base_dn: ou=people,dc=example,dc=com

ldap_connector.user_search_base: ou=people,dc=example,dc=com
ldap_connector.user_search_filter: (&(uid=*)(memberof=cn=permitta_users_gl,ou=groups,dc=example,dc=com))
ldap_connector.attr_user_name: uid
ldap_connector.attr_user_id: uid
ldap_connector.attr_first_name: givenname
ldap_connector.attr_last_name: sn
ldap_connector.attr_email: mail
ldap_connector.attr_groups: memberOf
ldap_connector.group_name_regex: "cn=([a-z_]*),."

trino_client.host: localhost
trino_client.port: "8081"
trino_client.username: admin

dbapi_connector.client_type: trino
dbapi_connector.data_object_table_column_query: |-
  select table_catalog || '.' || table_schema || '.' || table_name as fq_table_name
  from datalake.information_schema.tables

bundle_generator.temp_directory: /tmp
bundle_generator.static_rego_file_path: permitta-core/test/test_data/rego

api.healthcheck.api_key: a-secret-api-key