apiVersion: batch/v1
kind: CronJob
metadata:
  name: principal-ingestion
spec:
  schedule: "0 */6 * * *"  # Run every 6 hours
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: permitta
            image: permitta-core:latest
            imagePullPolicy: IfNotPresent
            args: ["ingest","--connector-name=ldap", "--object-type=principal"]
            env:
              - name: CONFIG_FILE_PATH
                value: "/app/permitta-core/config/config.principal_ingestion.yaml"
            volumeMounts:
            - name: ingestion-config
              mountPath: /app/permitta-core/config
              readOnly: true
          volumes:
          - name: ingestion-config
            configMap:
              name: permitta-ingestion-config
          restartPolicy: OnFailure