apiVersion: apps/v1
kind: Deployment
metadata:
  name: moat-api
  labels:
    app: moat-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: moat-api
  template:
    metadata:
      labels:
        app: moat-api
    spec:
      containers:
      - name: base
        image: moat:latest
        imagePullPolicy: IfNotPresent
        args: ["start-server"]
        ports:
        - containerPort: 8000
        env:
        - name: CONFIG_FILE_PATH
          value: "/app/moat/config/config.yaml"
        volumeMounts:
        - name: rego-config
          mountPath: /app/opa/moat
      volumes:
      - name: rego-config
        configMap:
          name: rego-config
