"""adds entitlements to principal object

Revision ID: 91ab5ec360d2
Revises: abc5cb051f3c
Create Date: 2025-09-13 00:34:15.617336+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '91ab5ec360d2'
down_revision: Union[str, Sequence[str], None] = 'abc5cb051f3c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('principals', sa.Column('entitlements', postgresql.ARRAY(sa.String()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('principals', 'entitlements')
    # ### end Alembic commands ###
