"""adds groups table

Revision ID: abc5cb051f3c
Revises: bd0cd0984a83
Create Date: 2025-09-08 07:58:11.675574+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'abc5cb051f3c'
down_revision: Union[str, Sequence[str], None] = 'bd0cd0984a83'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('principal_groups',
    sa.Column('principal_group_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('fq_name', sa.String(), nullable=True),
    sa.Column('members', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('source_type', sa.String(), nullable=True),
    sa.Column('source_uid', sa.String(), nullable=True),
    sa.Column('scim_payload', sa.JSON(), nullable=True),
    sa.Column('ingestion_process_id', sa.Integer(), nullable=True),
    sa.Column('active', sa.Boolean(), server_default='t', nullable=True),
    sa.PrimaryKeyConstraint('principal_group_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('principal_groups')
    # ### end Alembic commands ###
