name: Build, Test, and Push Docker Image

on:
  push:
    branches: [ main ]

jobs:
  build-test-push:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:16
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: password
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Get version
      id: get_version
      run: echo "VERSION=$(cat version.txt)" >> $GITHUB_OUTPUT

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3

#    - name: Login to DockerHub
#      if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/master'
#      uses: docker/login-action@v2
#      with:
#        username: ${{ secrets.DOCKERHUB_USERNAME }}
#        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build Docker image
      uses: docker/build-push-action@v4
      with:
        context: .
        platforms: linux/amd64,linux/arm64
        load: true
        push: false
        tags: |
          permitta/permitta-core:${{ steps.get_version.outputs.VERSION }}
          permitta/permitta-core:latest
        cache-from: type=gha
        cache-to: type=gha,mode=max

    - name: Run OPA tests
      run: |
        # Run OPA tests
        docker run --rm permitta/permitta-core:${{ steps.get_version.outputs.VERSION }} test opa

    - name: Run Unit tests
      run: |
        # Run unit tests
        docker run --rm --network=host permitta/permitta-core:${{ steps.get_version.outputs.VERSION }} test unit

    - name: Run CLI tests
      run: |
        # Test CLI functionality
        docker run --rm permitta/permitta-core:${{ steps.get_version.outputs.VERSION }} --help

#    - name: Push Docker image
#      if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/master'
#      uses: docker/build-push-action@v4
#      with:
#        context: .
#        push: true
#        tags: |
#          permitta/permitta-core:${{ steps.get_version.outputs.VERSION }}
#          permitta/permitta-core:latest
#        cache-from: type=gha
#        cache-to: type=gha,mode=max
